#pragma once

#ifndef AUTONOMOUS_INTERVAL_MS
#define AUTONOMOUS_INTERVAL_MS 10000UL
#endif

#ifndef AUTONOMOUS_RESPONSE_TIMEOUT_MS
#define AUTONOMOUS_RESPONSE_TIMEOUT_MS 8000UL
#endif

#ifndef AUTONOMOUS_FIRST_PAGE_SIZE
#define AUTONOMOUS_FIRST_PAGE_SIZE 1
#endif

#ifndef AUTONOMOUS_MAX_PAGE_SIZE
#define AUTONOMOUS_MAX_PAGE_SIZE 25
#endif
