#pragma once

#ifndef AUTONOMOUS_INTERVAL_MS
#define AUTONOMOUS_INTERVAL_MS 600000UL
#endif

#ifndef AUTONOMOUS_RESPONSE_TIMEOUT_MS
#define AUTONOMOUS_RESPONSE_TIMEOUT_MS 8000UL
#endif

#ifndef AUTONOMOUS_LOG_PAGE_SIZE
#define AUTONOMOUS_LOG_PAGE_SIZE 6
#endif

#ifndef AUTONOMOUS_CONTROLLER_RETRY_MS
#define AUTONOMOUS_CONTROLLER_RETRY_MS 5000UL
#endif

#ifndef AUTONOMOUS_CONTROLLER_MAX_ATTEMPTS
#define AUTONOMOUS_CONTROLLER_MAX_ATTEMPTS 3
#endif

#ifndef AUTONOMOUS_HEALTH_CHECK_INTERVAL_MS
#define AUTONOMOUS_HEALTH_CHECK_INTERVAL_MS 60000UL
#endif

#ifndef AUTONOMOUS_DEGRADED_RETRY_MS
#define AUTONOMOUS_DEGRADED_RETRY_MS 60000UL
#endif

#ifndef AUTONOMOUS_LOG_FAILURES_BEFORE_AUDIT
#define AUTONOMOUS_LOG_FAILURES_BEFORE_AUDIT 2
#endif

#ifndef AUTONOMOUS_MIN_VALID_EPOCH
#define AUTONOMOUS_MIN_VALID_EPOCH 1704067200UL
#endif

#ifndef AUTONOMOUS_TIME_DRIFT_TOLERANCE_SEC
#define AUTONOMOUS_TIME_DRIFT_TOLERANCE_SEC 30UL
#endif
