#pragma once

#ifndef AUTONOMOUS_INTERVAL_MS
#define AUTONOMOUS_INTERVAL_MS 600000UL
#endif

#ifndef AUTONOMOUS_RESPONSE_TIMEOUT_MS
#define AUTONOMOUS_RESPONSE_TIMEOUT_MS 8000UL
#endif

#ifndef AUTONOMOUS_LOG_PAGE_SIZE
#define AUTONOMOUS_LOG_PAGE_SIZE 6
#endif

#ifndef AUTONOMOUS_CONTROLLER_RETRY_MS
#define AUTONOMOUS_CONTROLLER_RETRY_MS 5000UL
#endif

#ifndef AUTONOMOUS_CONTROLLER_MAX_ATTEMPTS
#define AUTONOMOUS_CONTROLLER_MAX_ATTEMPTS 3
#endif

#ifndef AUTONOMOUS_MODE_AUDIT_INTERVAL_MS
#define AUTONOMOUS_MODE_AUDIT_INTERVAL_MS 86400000UL
#endif

#ifndef AUTONOMOUS_DEGRADED_RETRY_MS
#define AUTONOMOUS_DEGRADED_RETRY_MS 300000UL
#endif

#ifndef AUTONOMOUS_LOG_FAILURES_BEFORE_AUDIT
#define AUTONOMOUS_LOG_FAILURES_BEFORE_AUDIT 2
#endif
