#pragma once

#define FIRMWARE_MODE_MANUAL 0
#define FIRMWARE_MODE_AUTONOMOUS 1

#ifndef FIRMWARE_RUN_MODE
#define FIRMWARE_RUN_MODE FIRMWARE_MODE_MANUAL
#endif

#if FIRMWARE_RUN_MODE != FIRMWARE_MODE_MANUAL && \
    FIRMWARE_RUN_MODE != FIRMWARE_MODE_AUTONOMOUS
#error "FIRMWARE_RUN_MODE must be FIRMWARE_MODE_MANUAL or FIRMWARE_MODE_AUTONOMOUS"
#endif
